---
- name: Example playbook using AWX credentials
  hosts: localhost
  gather_facts: no
  vars:
    # Reference to the credentials stored in AWX
    # This does not print the credentials but shows how to reference them
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

  tasks:
    - name: Placeholder task using AWS credentials
      debug:
        msg: "Using AWS credentials securely without printing them"
